// <auto-generated />
using System;
using FlorescerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlorescerAPI.Migrations
{
    [DbContext(typeof(MinimalContextDb))]
    [Migration("20230514181754_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlorescerAPI.Models.Planta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Appeal")
                        .HasColumnType("varchar");

                    b.Property<string>("Avaibility")
                        .HasColumnType("varchar");

                    b.Property<string>("AvaibleSizesPot")
                        .HasColumnType("varchar");

                    b.Property<string>("Bearing")
                        .HasColumnType("varchar");

                    b.Property<string>("BloomingSeason")
                        .HasColumnType("varchar");

                    b.Property<string>("Categorie")
                        .HasColumnType("varchar");

                    b.Property<string>("Climat")
                        .HasColumnType("varchar");

                    b.Property<string>("ColorOfBloom")
                        .HasColumnType("varchar");

                    b.Property<string>("ColorOfLeaf")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .HasColumnType("varchar");

                    b.Property<string>("Desease")
                        .HasColumnType("varchar");

                    b.Property<string>("Family")
                        .HasColumnType("varchar");

                    b.Property<string>("Growth")
                        .HasColumnType("varchar");

                    b.Property<string>("HeightAtPurchase")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("HeightPotential")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Img")
                        .HasColumnType("varchar");

                    b.Property<string>("Insect")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("LatinName")
                        .HasColumnType("varchar");

                    b.Property<string>("LightIdeal")
                        .HasColumnType("varchar");

                    b.Property<string>("LightTolered")
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar");

                    b.Property<string>("OtherName")
                        .HasColumnType("varchar");

                    b.Property<string>("Perfume")
                        .HasColumnType("varchar");

                    b.Property<string>("PotDiameter")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Pruning")
                        .HasColumnType("varchar");

                    b.Property<string>("Style")
                        .HasColumnType("varchar");

                    b.Property<string>("TemperatureMax")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("TemperatureMin")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Url")
                        .HasColumnType("varchar");

                    b.Property<string>("Use")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Watering")
                        .HasColumnType("varchar");

                    b.Property<string>("WidthAtPurchase")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("WidthPotential")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Plantas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
